* config/announce-gen, Makefile.cfg: New. * Makefile.am: Adjust. * GNUmakefile, Makefile.maint: Update from CVS Autoconf, but keeping local WGET and WGETFLAGS modifications from Paul Eggert.

diff --git a/Makefile.maint b/Makefile.maint
--- a/Makefile.maint
+++ b/Makefile.maint
@@ -1,8 +1,8 @@
 # -*-Makefile-*-
-# This Makefile fragment is shared between fileutils, sh-utils, textutils,
+# This Makefile fragment is shared between the coreutils,
 # CPPI, Bison, and Autoconf.
 
-## Copyright (C) 2001, 2002, 2003 Free Software Foundation, Inc.
+## Copyright (C) 2001-2003 Free Software Foundation, Inc.
 ##
 ## This program is free software; you can redistribute it and/or modify
 ## it under the terms of the GNU General Public License as published by
@@ -19,27 +19,33 @@
 ## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 ## 02111-1307, USA.
 
+# This is reported not to work with make-3.79.1
+# ME := $(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST))
+ME := Makefile.maint
+
 # Do not save the original name or timestamp in the .tar.gz file.
-GZIP_ENV = '--no-name --best'
+GZIP_ENV = '--no-name --best --rsyncable'
 
 CVS = cvs
 
-prev_version_file ?= .prev-version
+ifeq ($(origin prev_version_file), undefined)
+  prev_version_file = .prev-version
+endif
 
-THIS_VERSION_REGEXP = $(subst .,\.,$(VERSION))
 PREV_VERSION := $(shell cat $(prev_version_file))
-PREV_VERSION_REGEXP := $(shell echo $(PREV_VERSION)|sed 's/\./\\./g')
 
 tag-package = $(shell echo "$(PACKAGE)" | tr '[:lower:]' '[:upper:]')
 tag-this-version = $(subst .,_,$(VERSION))
-tag-prev-version = $(subst .,_,$(PREV_VERSION))
 this-cvs-tag = $(tag-package)-$(tag-this-version)
-prev-cvs-tag = $(tag-package)-$(tag-prev-version)
 my_distdir = $(PACKAGE)-$(VERSION)
 
 # Old releases are stored here.
 # Used for diffs and xdeltas.
 release_archive_dir ?= ../release
+
+# Prevent programs like 'sort' from considering distinct strings to be equal.
+# Doing it here saves us from having to set LC_ALL elsewhere in this file.
+export LC_ALL = C
 
 
 
@@ -50,20 +56,133 @@ release_archive_dir ?= ../release
 # Checks that don't require cvs.
 # Run `changelog-check' last, as previous test may reveal problems requiring
 # new ChangeLog entries.
-local-check = \
+local-checks-available = \
   po-check copyright-check writable-files m4-check author_mark_check \
-  changelog-check strftime-check header-check
-.PHONY: $(local-check)
+  changelog-check strftime-check syntax-check makefile_path_separator_check \
+  makefile-check
+.PHONY: $(local-checks-available)
+
+local-check = $(filter-out $(local-checks-to-skip), $(local-checks-available))
 
 # Make sure C source files in src/ don't include xalloc.h directly,
 # since they all already include it via sys2.h.
 # It's not a big deal -- just aesthetics.
-header-check:
-	if test -f $(srcdir)/src/sys2.h; then				\
+.PHONY: $(syntax-check-rules)
+syntax-check-rules = \
+  sc_cast_of_argument_to_free \
+  sc_cast_of_x_alloc_return_value \
+  sc_changelog \
+  sc_error_exit_success \
+  sc_space_tab \
+  sc_sun_os_names \
+  sc_system_h_headers \
+  sc_unmarked_diagnostics \
+  sc_xalloc_h_in_src
+
+syntax-check: $(syntax-check-rules)
+#	@grep -E '#  *include <(limits|std(def|arg|bool))\.h>'		\
+#	    $$(find -type f -name '*.[chly]') &&			\
+#	  { echo '$(ME): found conditional include' 1>&2;		\
+#	    exit 1; } || :
+
+#	grep -E '^#  *include <(string|stdlib)\.h>'			\
+#	    $(srcdir)/{lib,src}/*.[chy] &&				\
+#	  { echo '$(ME): FIXME' 1>&2;					\
+#	    exit 1; } || :
+# FIXME: don't allow `#include .strings\.h' anywhere
+
+# Look for diagnostics that aren't marked for translation.
+# This won't find any for which error's format string is on a separate line.
+sc_unmarked_diagnostics:
+	@grep --exclude=$(srcdir)/src/shred.c -E			\
+	    '\<error \([^"]*"[^"]*[a-z]{3}' $(srcdir)/{lib,src}/*.c	\
+	  | grep -v '_(' &&						\
+	  { echo '$(ME): found unmarked diagnostic(s)' 1>&2;		\
+	    exit 1; } || :
+
+sc_cast_of_argument_to_free:
+	@grep -E '\<free \(\(' $(srcdir)/{lib,src}/*.[chly] &&		\
+	  { echo '$(ME): don'\''t cast free argument' 1>&2;		\
+	    exit 1; } || :
+
+sc_cast_of_x_alloc_return_value:
+	@grep -E --exclude=$(srcdir)/lib/regex.c			\
+	    '\*\) *x(m|c|re)alloc\>' $(srcdir)/{lib,src}/*.[chy] &&	\
+	  { echo '$(ME): don'\''t cast x*alloc return value' 1>&2;	\
+	    exit 1; } || :
+
+sc_space_tab:
+	@( cvsu --list ) > /dev/null 2>&1 || : &&			\
+	  grep '[ ]	'						\
+	     $$(cvsu --list | grep -vEf .x-$@ ) &&			\
+	  { echo '$(ME): found SPACE-TAB sequence; remove the SPACE'	\
+		1>&2; exit 1; } || :
+
+# Using EXIT_SUCCESS as the first argument to error is misleading,
+# since when that parameter is 0, error does not exit.  Use `0' instead.
+sc_error_exit_success:
+	@grep -F 'error (EXIT_SUCCESS,'					\
+	    $$(find -type f -name '*.[chly]') &&			\
+	  { echo '$(ME): found error (EXIT_SUCCESS' 1>&2;		\
+	    exit 1; } || :
+
+# FIXME: merge this with sc_system_h_headers below.
+# xalloc.h is included via system.h, so should not be included
+# directly by any file in src/.
+sc_xalloc_h_in_src:
+	@if test -f $(srcdir)/src/sys2.h; then				\
 	  if grep 'xalloc\.h' $(srcdir)/src/*.c; then			\
 	    exit 1;							\
 	  fi;								\
 	fi
+
+# FIXME: warn about definitions of EXIT_FAILURE, EXIT_SUCCESS, STREQ
+
+# Each nonempty line must start with a year number, or a TAB.
+sc_changelog:
+	@grep '^[^12	]' $$(find . -name ChangeLog -maxdepth 2) &&	\
+	  { echo '$(ME): found unexpected prefix in a ChangeLog' 1>&2;	\
+	    exit 1; } || :
+
+header_regexp = \
+  alloca\
+  |closeout\
+  |ctype\
+  |dirent\
+  |errno\
+  |fcntl\
+  |inttypes\
+  |limits\
+  |locale\
+  |pathmax\
+  |std(lib|bool)\
+  |string\
+  |sys/(stat|dir|time)\
+  |time\
+  |unistd\
+  |utime\
+  |version-etc\
+  |xalloc
+h_re := $(shell echo '$(header_regexp)'|tr -d ' ')
+
+# Files in src/ should not include directly any of
+# the headers already included via system.h.
+# Get list of candidates with this:
+# grep -h include src/sys*.h|sed 's/.*include //'|sort -
+sc_system_h_headers:
+	@( cvsu --list ) > /dev/null 2>&1 || : &&			\
+	grep -E '^# *include ["<]($(h_re))\.h[">]'			\
+	    $$(cvsu --list src | grep -Ev 'sys(2|tem)\.h$$')		\
+	  && { echo '$(ME): the above are already included via system.h'\
+		1>&2; exit 1; } || :
+
+sc_sun_os_names:
+	@( cvsu --list ) > /dev/null 2>&1 || : && \
+	grep -Ei \
+	    'solaris[^[:alnum:]]*2\.(7|8|9|[1-9][0-9])|sunos[^[:alnum:]][6-9]' \
+	  $$(cvsu --list | grep -vEf .x-$@ ) &&			\
+	  { echo '$(ME): found misuse of Sun OS version numbers' 1>&2;	\
+	    exit 1; } || :
 
 # Ensure that date's --help output stays in sync with the info
 # documentation for GNU strftime.  The only exception is %N,
@@ -79,6 +198,13 @@ strftime-check:
 	  diff -u $@-src $@-info || exit 1;				\
 	  rm -f $@-src $@-info;						\
 	fi
+
+# Ensure that we use only the standard $(VAR) notation,
+# not @...@ in Makefile.am, now that we can rely on automake
+# to emit a definition for each substituted variable.
+makefile-check:
+	grep -E '@[A-Z_0-9]+@' `find . -name Makefile.am` \
+	  && { echo 'Makefile.maint: use $(...), not @...@' 1>&2; exit 1; } || :
 
 changelog-check:
 	if head ChangeLog | grep 'Version $(VERSION)' >/dev/null; then \
@@ -119,6 +245,17 @@ author_mark_check:
 	  { echo 'Makefile.maint: enclose the above strings in N_ (...)' 1>&2; \
 	    exit 1; } || :
 
+# Sometimes it is useful to change the PATH environment variable
+# in Makefiles.  When doing so, it's better not to use the Unix-centric
+# path separator of `:', but rather the automake-provided `@PATH_SEPARATOR@'.
+# It'd be better to use `find -print0 ...|xargs -0 ...', but less portable,
+# and there probably aren't many projects with so many Makefile.am files
+# that we'd have to worry about limits on command line length.
+msg = 'Makefile.maint: Do not use `:'\'' above; use @PATH_SEPARATOR@ instead'
+makefile_path_separator_check:
+	@grep 'PATH=.*:' `find $(srcdir) -name Makefile.am` \
+	  && { echo $(msg) 1>&2; exit 1; } || :
+
 # Check that `make alpha' will not fail at the end of the process.
 writable-files:
 	if test -d $(release_archive_dir); then :; else			\
@@ -153,10 +290,10 @@ cvs-tag-check:
 	else :; fi
 
 cvs-diff-check:
-	if $(CVS) diff >cvs-diffs; then			  	\
-	  rm cvs-diffs;					  	\
-	else						  	\
-	  echo "Some files are locally modified:" 1>&2;  	\
+	if $(CVS) diff >cvs-diffs; then				\
+	  rm cvs-diffs;						\
+	else							\
+	  echo "Some files are locally modified:" 1>&2;		\
 	  cat cvs-diffs;					\
 	  exit 1;						\
 	fi
@@ -189,10 +326,11 @@ null_AM_MAKEFLAGS = \
 # by the use of _().  The --disable-nls effectively defines away that macro,
 # and building with CFLAGS='-Wformat -Werror' causes any format warning to be
 # treated as a failure.
-t=./=test
+TMPDIR ?= /tmp
+t=$(TMPDIR)/$(PACKAGE)/test
 my-distcheck: $(local-check)
 	-rm -rf $(t)
-	mkdir $(t)
+	mkdir -p $(t)
 	GZIP=$(GZIP_ENV) $(AMTAR) -C $(t) -zxf $(distdir).tar.gz
 	cd $(t)/$(distdir) \
 	  && ./configure --disable-nls \
@@ -201,8 +339,8 @@ my-distcheck: $(local-check)
 	  && $(MAKE) dvi \
 	  && $(MAKE) check \
 	  && $(MAKE) distclean
-	cd $(t) && mv $(distdir) $(distdir).old \
-	  && $(AMTAR) -zxf ../$(distdir).tar.gz
+	(cd $(t) && mv $(distdir) $(distdir).old \
+	  && $(AMTAR) -zxf - ) < $(distdir).tar.gz
 	diff -ur $(t)/$(distdir).old $(t)/$(distdir)
 	-rm -rf $(t)
 	@echo "========================"; \
@@ -234,47 +372,22 @@ rel-check:
 prev-tgz = $(PACKAGE)-$(PREV_VERSION).tar.gz
 xd-delta = $(PACKAGE)-$(PREV_VERSION)-$(VERSION).xdelta
 
-news-r1 = /^[^ ].*$(THIS_VERSION_REGEXP)[]:]/
-news-r2 = /^[^ ].*$(PREV_VERSION_REGEXP)[]:]/
+signatures ?= $(distdir).tar.bz2.asc $(distdir).tar.gz.asc
+%.asc: %
+	rm -f $@
+	gpg --armor --detach-sign -o $@ $<
 
-rel-files = $(xd-delta) $(distdir).tar.bz2 $(distdir).tar.gz
-announcement: NEWS ChangeLog $(rel-files)
-	@( \
-	  echo Subject: $(my_distdir) released; \
-	  echo; \
-	  echo FIXME: put comments here; \
-	  echo; \
-	  for url in $(url_dir_list); do \
-	    echo "  $$url/$(my_distdir).tar.gz   ($(tgz-size))"; \
-	    echo "  $$url/$(my_distdir).tar.bz2  ($(bz2-size))"; \
-	  done; \
-	  echo; \
-	  echo And here are xdelta-style diffs; \
-	  echo; \
-	  for url in $(url_dir_list); do \
-	    echo "  $$url/$(xd-delta)   ($(xd-size))"; \
-	  done; \
-	  echo; \
-	  echo "Here are the MD5 and SHA1 signatures:"; \
-	  echo; \
-	  echo "$(tgz-md5)  $(my_distdir).tar.gz"; \
-	  echo "$(bz2-md5)  $(my_distdir).tar.bz2"; \
-	  echo "$(xdelta-md5)  $(xd-delta)"; \
-	  echo "$(tgz-sha1)  $(my_distdir).tar.gz"; \
-	  echo "$(bz2-sha1)  $(my_distdir).tar.bz2"; \
-	  echo "$(xdelta-sha1)  $(xd-delta)"; \
-	  echo; \
-	  echo NEWS:; \
-	  sed -n "$(news-r1),$(news-r2)p" NEWS \
-	    | grep -v '^\['; \
-	  echo; \
-	  echo ChangeLog entries:; \
-	  find . -name ChangeLog -maxdepth 2 \
-	    | xargs $(CVS) diff -up -r$(prev-cvs-tag) -rHEAD \
-	    | sed -n 's/^+//p' \
-	    | perl -ne 'm!^\+\+ (\./)?! or print,next;' \
-	      -e 'print "\n"."*"x70 ."\n"; s///; print; print "*"x70 ."\n"'; \
-	)
+rel-files = $(xd-delta) $(distdir).tar.bz2 $(distdir).tar.gz $(signatures)
+announce_gen ?= ./announce-gen
+announcement: NEWS ChangeLog $(rel-files) $(signatures)
+	@$(announce_gen)						\
+	    --release-type=$(RELEASE_TYPE)				\
+	    --package=$(PACKAGE)					\
+	    --prev=$(PREV_VERSION)					\
+	    --curr=$(VERSION)						\
+	    --release-archive-directory=$(release_archive_dir)		\
+	    --news=NEWS							\
+	    $(addprefix --url-dir=, $(url_dir_list))			\
 
 
 ## ---------------- ##
@@ -282,6 +395,7 @@ announcement: NEWS ChangeLog $(rel-files)
 ## ---------------- ##
 
 ftp-gnu = ftp://ftp.gnu.org/gnu
+www-gnu = http://www.gnu.org
 
 # Use mv, if you don't have/want move-if-change.
 move_if_change ?= move-if-change
@@ -306,7 +420,8 @@ do-po-update:
 	tmppo=/tmp/$(PACKAGE)-$(VERSION)-po &&\
 	rm -rf $$tmppo && \
 	mkdir $$tmppo && \
-	(cd $$tmppo && $(WGET) $(WGETFLAGS) -r -l1 -nd --no-parent -A '*.po' $(po_repo)) &&\
+	(cd $$tmppo && \
+	  $(WGET) $(WGETFLAGS) -r -l1 -nd --no-parent -A '*.po' $(po_repo)) &&\
 	cp $$tmppo/*.po po
 	cd po && $(MAKE) update-po
 	$(MAKE) po-check
@@ -336,8 +451,8 @@ ansi2knr.c-url_prefix = ftp://ftp.cs.wisc.edu/ghost/
 
 texinfo.tex-url_prefix = $(ftp-gnu)/texinfo/
 
-standards.texi-url_prefix = $(ftp-gnu)/GNUinfo/
-make-stds.texi-url_prefix = $(ftp-gnu)/GNUinfo/
+standards.texi-url_prefix = $(www-gnu)/prep/
+make-stds.texi-url_prefix = $(standards.texi-url_prefix)
 
 target = $(patsubst get-%, %, $@)
 url = $($(notdir $(target))-url_prefix)$(notdir $(target))
@@ -347,21 +462,30 @@ $(get-targets):
 	$(WGET) $(WGETFLAGS) $(url) -O $(target).t \
 	  && $(move_if_change) $(target).t $(target)
 
-cvs_files ?= $(srcdir)/config/depcomp $(srcdir)/config/missing $(srcdir)/config/mkinstalldirs \
-             $(srcdir)/config/install-sh $(srcdir)/src/ansi2knr.c
+cvs_files ?= \
+  $(srcdir)/src/ansi2knr.c \
+  $(srcdir)/config/depcomp \
+  $(srcdir)/config/install-sh \
+  $(srcdir)/config/missing \
+  $(srcdir)/config/mkinstalldirs
 automake_repo=:pserver:anoncvs:anoncvs@sources.redhat.com:/cvs/automake
 .PHONY: wget-update
 wget-update: $(get-targets)
 
 .PHONY: cvs-update
 cvs-update:
-	for f in $(cvs_files); do				      \
-	  test -f $$f || { echo "*** skipping $$f" 1>&2; continue; }; \
-	  file=`basename $$f`;					      \
-	  echo checking out $$file...;				      \
-	  $(CVS) -d $(automake_repo) co -p automake/lib/$$file> $$f.t \
-	    && $(move_if_change) $$f.t $$f;			      \
-	done
+	fail=;								\
+	for f in $(cvs_files); do					\
+	  test -f $$f || { echo "*** skipping $$f" 1>&2; continue; };	\
+	  cvs diff $$f > /dev/null					\
+	    || { echo "*** $$f is locally modified; skipping it" 1>&2;	\
+		 fail=yes; continue; };					\
+	  file=$$(basename $$f);					\
+	  echo checking out $$file...;					\
+	  $(CVS) -d $(automake_repo) co -p automake/lib/$$file> $$f.t	\
+	    && $(move_if_change) $$f.t $$f;				\
+	done;								\
+	test "$$fail" && exit 1
 
 define emit-upload-commands
 	echo =====================================
@@ -375,10 +499,11 @@ endef
 $(xd-delta): $(release_archive_dir)/$(prev-tgz) $(distdir).tar.gz
 	xdelta delta -9 $^ $@ || :
 
-alpha: $(local-check)
+.PHONY: alpha beta major
+alpha beta major: $(local-check)
 	$(MAKE) cvs-dist
 	$(MAKE) $(xd-delta)
-	$(MAKE) -s announcement > /tmp/announce-$(my_distdir)
+	$(MAKE) -s announcement RELEASE_TYPE=$@ > /tmp/announce-$(my_distdir)
 	ln $(rel-files) $(release_archive_dir)
 	chmod a-w $(rel-files)
 	echo $(VERSION) > $(prev_version_file)
