examples: check the variant example
* examples/mfcalc/local.mk, examples/rpcalc/local.mk: Define the
programs in a more natural order, source, preproc, then linker.

* examples/test: Be ready to work on programs that are not in
a subdir.
* examples/variant.test: New.
* examples/local.mk: Use it.
* examples/variant.yy: Don't use 0 for nullptr.
Use a more natural output for a list of string.

diff --git a/examples/test b/examples/test
--- a/examples/test
+++ b/examples/test
@@ -27,7 +27,18 @@ exit=true
 cwd=`pwd`
 
 # The exercised program.
-prog=$cwd/examples/$me/$me
+for p in $cwd/examples/$me/$me $cwd/examples/$me
+do
+    if test -x "$p"; then
+        prog=$p
+        break
+    fi
+done
+if test x"$prog" = x; then
+    echo "$me: ERROR: cannot find program to exercise"
+    exit 1
+fi
+
 
 # cleanup
 # -------
